name: Build with Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  OpenSSL-Build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Checkout netty-tcnative repository
      uses: actions/checkout@v4
      with:
        repository: netty/netty-tcnative
        path: netty-tcnative
        ref: netty-tcnative-parent-2.0.67.Final

    - name: Create build
      run: docker compose up

    - name: Upload build file
      uses: actions/upload-artifact@v4
      with:
        name: libnetty-tcnative
        path: netty-tcnative/openssl-static/target/native-jar-work/META-INF/native/libnetty_tcnative_linux_x86_64.so
